=== RileySimsIT/XML-Timetable-Project/instanceSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="timetable">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="week">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="day" maxOccurs="5" minOccurs="5"> <!-- exactly 5 days in a week -->
                  <xs:complexType>
                  <xs:sequence>
                    <xs:element name="class" minOccurs="0" maxOccurs="13"> <!-- between 0 and 13 classes in a day-->
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="time" maxOccurs="13"> <!-- minimum of 1 hour per class maximum of 13-->
                            <xs:simpleType>
                              <xs:restriction base="xs:unsignedInt"> <!-- restricting input for the time values -->
                                <xs:enumeration value="800"/>
                                <xs:enumeration value="900"/>
                                <xs:enumeration value="1000"/>
                                <xs:enumeration value="1100"/>
                                <xs:enumeration value="1200"/>
                                <xs:enumeration value="1300"/>
                                <xs:enumeration value="1400"/>
                                <xs:enumeration value="1500"/>
                                <xs:enumeration value="1600"/>
                                <xs:enumeration value="1700"/>
                                <xs:enumeration value="1800"/>
                                <xs:enumeration value="1900"/>
                                <xs:enumeration value="2000"/>
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="code" use="required"/> <!-- require attributes for each class -->
                        <xs:attribute name="room" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="date" use="required"> <!-- required date attribute to identify day -->
                    <xs:simpleType>
                      <xs:restriction base="xs:ID">
                        <xs:enumeration value="Monday"/>
                        <xs:enumeration value="Tuesday"/>
                        <xs:enumeration value="Wednesday"/>
                        <xs:enumeration value="Thursday"/>
                        <xs:enumeration value="Friday"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="name" use="required"/>
      <xs:attribute name="id" type="xs:unsignedInt" use="required"/>
      <xs:attribute name="program"/>
      <xs:attribute name="school"/>
      <xs:attribute name="term" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== RileySimsIT/XML-Timetable-Project/instance2.xml
<?xml version="1.0" encoding="utf-8"?>
<!--program name and school are not required -->
<timetable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="instanceSchema.xsd"
           name="Emily"
           id="0123456"
           term="f2017">
  <!-- A week of class with exactly 5 days of the week-->
  <week>
    <day date="Monday">
      <!--classes are optional and dont have to occur on a day-->
    </day>
    <day date="Tuesday">
      <class code="ARTS-123" room="A1020">
        <time>1100</time>
      </class>
    </day>
    <day date="Wednesday">
      <class code="ARTS-123" room="D1234">
        <!--several occurances of time may occur for a class-->
        <time>800</time>
        <time>900</time>
        <time>1000</time>
        <time>1100</time>
        <time>1200</time>
      </class>
    </day>
    <day date="Thursday">
      <class code="TEST-5678" room="b1075">
        <time>2000</time>
      </class>
    </day>
    <day date="Friday">
      <class code="TEST-312" room="G1025">
        <time>1500</time>
        <time>1600</time>
        <time>1700</time>
      </class>
    </day>
  </week>
</timetable>

=== RileySimsIT/XML-Timetable-Project/instance1.xml
<?xml version="1.0" encoding="utf-8"?>
<!--program name and school are not required -->
<timetable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="instanceSchema.xsd"
           name="Riley"
           id="0746826"
           program="IWD"
           school="Fanshawe"
           term="w2018">
  <!-- A week of class with exactly 5 days of the week-->
  <week>
    <day date="Monday"> 
      <class code="TEST-123" room="G1234">
        <!--several occurances of time may occur for a class-->

        <time>800</time>
        <time>900</time>
      </class>

      <class code="TECH-1337" room="A1047">
        <time>1400</time>
        <time>1500</time>
        <time>1600</time>
      </class>
    </day>
    <day date="Tuesday">
      <class code="INFO-1234" room="r1020">
        <time>1100</time>
        <time>1200</time>
        <time>1300</time>
        <time>1400</time>
      </class>
      <class code="TECH-192" room="r1020">
        <!-- multiple classes at the same time doesn't overwrite the previous this can be easily changed but I left it in as a tool to show scheduling has been done wrong rather than overwriting-->
        <time>1400</time> 
        <time>1500</time>
        <time>1600</time>
      </class>
      
    </day>
    <day date="Wednesday">
      <!--classes are optional and dont have to occur on a day-->
    </day>
    <day date="Thursday">
      <class code="TEST-5678" room="b1075">
        <time>1200</time> <!-- doesn't matter what order the time slots are in-->
        <time>1000</time>
        <time>1100</time>
      </class>
    </day>
    <day date="Friday">
      <class code="INFO-1234" room="r1020">
        <time>1100</time>
        <time>1200</time>
        <time>1300</time>
        <time>1400</time>
      </class>

      <class code="TEST-123" room="G1234">
        <time>800</time>
        <time>900</time>
      </class>
    </day>
  </week>  
</timetable>
